#!/bin/sh
# --- WAYLAND SESSION WRAPPER ---
# Sets up the Wayland environment and starts the window manager.

# Fix for Java apps in tiling WMs
export _JAVA_AWT_WM_NONREPARENTING=1

# XDG Desktop Portal
export XDG_CURRENT_DESKTOP=dwl

exec dwl -s "$HOME/dots/scripts/dwl-init" "$@"
