#!/bin/sh

if [ -f /tmp/notify_time ]; then
    exit 0
fi

temp=$(sensors | grep 'Package id 0' | awk '{print $4}' | tr -d '+°C')

if [ "${temp%.*}" -gt 80 ]; then
    echo "🔥 $temp°C"
else
    echo " $temp°C"
fi
